all:
  children:
    control_plane:
      hosts:
        k8s-control-plane-1:
          ansible_host: "{{ control_plane_ip_1 }}"
          ansible_user: root
          node_ip: "{{ control_plane_private_ip_1 }}"
          node_role: control-plane
          node_index: 1
        k8s-control-plane-2:
          ansible_host: "{{ control_plane_ip_2 }}"
          ansible_user: root
          node_ip: "{{ control_plane_private_ip_2 }}"
          node_role: control-plane
          node_index: 2
        k8s-control-plane-3:
          ansible_host: "{{ control_plane_ip_3 }}"
          ansible_user: root
          node_ip: "{{ control_plane_private_ip_3 }}"
          node_role: control-plane
          node_index: 3
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    workers:
      hosts:
        k8s-worker-1:
          ansible_host: "{{ worker_ip_1 }}"
          ansible_user: root
          node_ip: "{{ worker_private_ip_1 }}"
          node_role: worker
          node_index: 1
        k8s-worker-2:
          ansible_host: "{{ worker_ip_2 }}"
          ansible_user: root
          node_ip: "{{ worker_private_ip_2 }}"
          node_role: worker
          node_index: 2
        k8s-worker-3:
          ansible_host: "{{ worker_ip_3 }}"
          ansible_user: root
          node_ip: "{{ worker_private_ip_3 }}"
          node_role: worker
          node_index: 3
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    k8s_cluster:
      children:
        control_plane:
        workers:
      vars:
        # Cluster configuration
        cluster_name: "{{ cluster_name | default('hetzner-k8s-cluster') }}"
        kubernetes_version: "{{ kubernetes_version | default('1.28') }}"
        pod_cidr: "{{ pod_cidr | default('10.244.0.0/16') }}"
        service_cidr: "{{ service_cidr | default('10.96.0.0/12') }}"
        
        # Load balancer configuration
        api_server_lb_ip: "{{ api_server_lb_ip }}"
        
        # Container runtime
        container_runtime: containerd
        
        # CNI plugin
        cni_plugin: flannel
        
        # Storage configuration
        storage_class: local-path
        
        # Monitoring
        enable_monitoring: true
        
        # Rancher configuration
        rancher_password: "{{ rancher_password }}"
        
        # Default user configuration
        acceldata_ssh_key: "{{ acceldata_ssh_key }}"