all:
  children:
    k8s_nodes:
      hosts:
        {% for i in range(1, node_count + 1) %}
        k8s-node-{{ i }}:
          ansible_host: "{{ node_ip_{{ i }} }}"
          ansible_user: root
          node_ip: "{{ node_private_ip_{{ i }} }}"
          node_role: hybrid
          control_plane: {{ "true" if i <= 3 else "false" }}
          worker: true
          node_index: {{ i }}
        {% endfor %}
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    control_plane:
      hosts:
        {% for i in range(1, min(node_count, 3) + 1) %}
        k8s-node-{{ i }}:
        {% endfor %}
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    workers:
      hosts:
        {% for i in range(1, node_count + 1) %}
        k8s-node-{{ i }}:
        {% endfor %}
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    k8s_cluster:
      children:
        k8s_nodes:
      vars:
        # Cluster configuration
        cluster_name: "{{ cluster_name | default('hetzner-k8s-cluster') }}"
        kubernetes_version: "{{ kubernetes_version | default('1.28') }}"
        pod_cidr: "{{ pod_cidr | default('10.244.0.0/16') }}"
        service_cidr: "{{ service_cidr | default('10.96.0.0/12') }}"
        
        # Load balancer configuration
        api_server_lb_ip: "{{ api_server_lb_ip }}"
        
        # Container runtime
        container_runtime: containerd
        
        # CNI plugin
        cni_plugin: flannel
        
        # Storage configuration
        storage_class: local-path
        
        # Monitoring
        enable_monitoring: true
        
        # Rancher configuration
        rancher_password: "{{ rancher_password }}"
        
        # Default user configuration
        acceldata_ssh_key: "{{ acceldata_ssh_key }}"